Early Stage (MVP)
fgacyc/song-bank pull request #4
Opened 2024-03-21 08:26 UTC by rikashi-shifu

### Please tell us what you did
1. Created basic platform
2. Created a basic search function
3. Made it responsive

### Are there any concerns that may be raised?
Haven't done rendered chords & lyrics using a necessary library

### Please add which issue does this PR close below using ("closes #issue_number")
None

2024-03-21 08:51 UTC, ETCasual requested changes

2024-03-21 08:51 UTC, ETCasual commented on packages/frontend/src/pages/song/[song].tsx
> +    const loadSongList = async () => {
use `anonymous function` and `.then()` to avoid race conditions

2024-03-21 08:51 UTC, ETCasual commented on packages/frontend/src/pages/song/[song].tsx
> +  const getVideoId = (url: string) => {
use `[song]` as `router.query.song` instead

2024-03-30 20:20 UTC, fgacyc approved these changes
Approve for now

2024-03-30 20:21 UTC, merged